ALTER TABLE VOTES
DROP FOREIGN KEY FK_VOTES__CANDIDATES;

ALTER TABLE VOTES
DROP COLUMN CANDIDATES_ID;

ALTER TABLE VOTES
ADD COLUMN CAND_USERS_ID INT;

ALTER TABLE VOTES
DROP FOREIGN KEY FK_VOTES__USERS;

ALTER TABLE VOTES
DROP INDEX UX_USERS_CANDIDATES;

ALTER TABLE VOTES
ADD CONSTRAINT FK_VOTES__CANDUSERS FOREIGN KEY(CAND_USERS_ID) REFERENCES USERS(ID);

ALTER TABLE VOTES
ADD CONSTRAINT FK_VOTES__USERS FOREIGN KEY(USERS_ID) REFERENCES USERS(ID);



ALTER TABLE TEAM_VOTES
DROP FOREIGN KEY FK_VOTES__TEAM_CANDIDATES;

ALTER TABLE TEAM_VOTES
DROP COLUMN TEAM_CANDIDATES_ID;

ALTER TABLE TEAM_VOTES
ADD COLUMN TEAMS_ID INT;

ALTER TABLE TEAM_VOTES
DROP FOREIGN KEY FK_TEAM_VOTES__USERS;

ALTER TABLE TEAM_VOTES
DROP INDEX UX_USERS_TEAM_CANDIDATES;

ALTER TABLE TEAM_VOTES
ADD CONSTRAINT FK_TEAM_VOTES__TEAMS FOREIGN KEY(TEAMS_ID) REFERENCES TEAMS(ID);

ALTER TABLE TEAM_VOTES
ADD CONSTRAINT FK_TEAM_VOTES__USERS FOREIGN KEY(USERS_ID) REFERENCES USERS(ID);