ALTER TABLE COUNTRIES
DROP COLUMN LANGUAGE,
DROP FOREIGN KEY FK_COUNTRIES__LANGUAGES,
DROP COLUMN LANGUAGE_ID;

ALTER TABLE LANGUAGES
DROP PRIMARY KEY,
ADD COLUMN ID INT NOT NULL,
ADD PRIMARY KEY(ID);

ALTER TABLE LANGUAGES
CHANGE COLUMN ID ID INT AUTO_INCREMENT;

ALTER TABLE COUNTRIES
ADD COLUMN LANGUAGES_ID INT,
ADD CONSTRAINT FK_COUNTRIES__LANGUAGES FOREIGN KEY(LANGUAGES_ID) REFERENCES LANGUAGES(ID);

ALTER TABLE `pictures` 
CHANGE COLUMN `IMAGE` `IMAGE` TEXT NULL ,
ADD COLUMN `TYPE_OF_IMAGE` VARCHAR(45) NULL AFTER `LAST_MODIFIED_BY`;

ALTER TABLE `pictures` 
ADD COLUMN `ID_OF_USER` INT(11) NULL AFTER `TYPE_OF_IMAGE`;

ALTER TABLE `pictures` 
ADD CONSTRAINT FK_PICTURES__USER_ID FOREIGN KEY(ID_OF_USER)
REFERENCES USERS(ID);


