ALTER TABLE `users` 
ADD COLUMN `UID` LONGTEXT NULL AFTER `TEAMS_ID`;

ALTER TABLE `pictures` 
CHANGE COLUMN `IMAGE` `IMAGE` LONGTEXT NULL DEFAULT NULL ;


ALTER TABLE `pictures` 
CHANGE COLUMN `IMAGE` `IMAGE` LONGTEXT NULL DEFAULT NULL ;
