ALTER TABLE USERS CHANGE COLUMN TITLE TITLE ENUM('Mr', 'Mrs', 'Ms');

CREATE TABLE NEWS
(
	ID INT,
	TITLE VARCHAR(255),
	MESSAGE VARCHAR(255),
	LAST_MODIFIED_AT DATE,
    LAST_MODIFIED_BY VARCHAR(45),
	PRIMARY KEY(ID)
);

ALTER TABLE LANGUAGES
ADD LAST_MODIFIED_AT DATE;

ALTER TABLE LANGUAGES
ADD LAST_MODIFIED_BY VARCHAR(45);

ALTER TABLE MESSAGES
ADD LAST_MODIFIED_AT DATE;

ALTER TABLE MESSAGES
ADD LAST_MODIFIED_BY VARCHAR(45);

ALTER TABLE FAQS
ADD LAST_MODIFIED_AT DATE;

ALTER TABLE FAQS
ADD LAST_MODIFIED_BY VARCHAR(45);

ALTER TABLE PROJECTS
ADD LAST_MODIFIED_AT DATE;

ALTER TABLE PROJECTS
ADD LAST_MODIFIED_BY VARCHAR(45);

ALTER TABLE TEAMS
ADD LAST_MODIFIED_AT DATE;

ALTER TABLE TEAMS
ADD LAST_MODIFIED_BY VARCHAR(45);