CREATE TABLE about (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(45) NULL,
   TEXT VARCHAR(1500) NULL,
   LAST_MODIFIED_AT DATE NULL,
   LAST_MODIFIED_BY VARCHAR(45) NULL,
   PRIMARY KEY (ID));
