ALTER TABLE PROJECTS
ADD COLUMN PROJECT_NAME VARCHAR(255);

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE PERIODS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE CANDIDATES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE VOTES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE POSITIONS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE AGENCIES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE ROLES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE PROJECTS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE TEAMS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE COUNTRIES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE NEWS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE FAQS
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE TEAM_CANDIDATES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE TEAM_VOTES
MODIFY COLUMN ID INT AUTO_INCREMENT;

ALTER TABLE DEPARTMENTS
MODIFY COLUMN ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;