CREATE TABLE `contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(500) NULL,
  `address` VARCHAR(500) NULL,
  `telephone` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `LAST_MODIFIED_AT` VARCHAR(45) NULL,
  `LAST_MODIFIED_BY` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));
