ALTER TABLE VOTES
ADD COLUMN PERIOD_ID INT;

ALTER TABLE VOTES
ADD CONSTRAINT FK_VOTES__PERIODS FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(ID);

ALTER TABLE TEAM_VOTES
ADD COLUMN PERIOD_ID INT;

ALTER TABLE TEAM_VOTES
ADD CONSTRAINT FK_TEAM_VOTES__PERIODS FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(ID);

ALTER TABLE VOTES
ADD COLUMN DATE DATE;

ALTER TABLE TEAM_VOTES
ADD COLUMN DATE DATE;